<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header_new.php");
$APPLICATION->SetPageProperty("keywords", "Буфеты для для кухни и столовой | Купить в магазине &quot;Белорусская мебель&quot; буфет в Москве");
$APPLICATION->SetPageProperty("title", "Каталог белорусской мебели с ценами – заходите и выбирайте!");
$APPLICATION->SetPageProperty("description", "Нужна мебель из Беларуси? Интернет-магазин с полным каталогом белорусской мебели с ценами и фото. Гарантия - от 6 месяцев до 1 года. Доставка по Москве и России. Телефон: 8 (800) 555-10-32");
require($_SERVER["DOCUMENT_ROOT"]."/catalog/redirect.php");
require($_SERVER["DOCUMENT_ROOT"]."/catalog/newurl.php");
$APPLICATION->SetTitle("Каталог белорусской мебели с ценами");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"catalog2",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BASKET_URL" => "/personal/cart/",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COMPATIBLE_MODE" => "N",
		"COMPONENT_TEMPLATE" => "catalog2",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(0=>"",1=>"",),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(0=>"SLEEP_SIZE",1=>"MATERIAL",2=>"COLOR",3=>"SIZE",4=>"DIAMETR",5=>"",),
		"DETAIL_PROPERTY_CODE" => array(0=>"ARTNUMBER",1=>"BAZOVI_BLOCK_MAT",2=>"VID_POSTAVKI",3=>"HEIGHT",4=>"VISOTA_BEZ_CHEHLA",5=>"VISOTA_SPINKI",6=>"VISOTA_IZGOLOVIA",7=>"WARRANTY",8=>"DEPTH",9=>"CITY",10=>"DIAMETR",11=>"LENGHT",12=>"DLINA_MATRASA",13=>"P26",14=>"P25",15=>"DLINA_SPAL_MESTA",16=>"DOPUST_RAZ_VES",17=>"ZERKALO",18=>"P15",19=>"P24",20=>"P1",21=>"KOLVO_PAKETOV",22=>"P2",23=>"KOLVO_PRUJIN",24=>"P11",25=>"P20",26=>"KREPLENIE",27=>"MAX_NAGRUZKA",28=>"P13",29=>"P22",30=>"MATERIAL",31=>"P5",32=>"P10",33=>"MECH",34=>"P4",35=>"P8",36=>"NAL_MESTA",37=>"NALISHIE_MATRASA",38=>"P12",39=>"P21",40=>"OBIVKA",41=>"P14",42=>"P23",43=>"OBIEM",44=>"OTDELKA",45=>"MANUFACTURER",46=>"SIZE",47=>"RAZMER",48=>"RASPOLOHENIE",49=>"P9",50=>"SERIES",51=>"SERIA",52=>"SPOSOB_CHISTKI",53=>"RETURN",54=>"SROK_SLUHBI",55=>"STIL_MEB",56=>"COUNTRY",57=>"STRANA",58=>"SEMNI_CHEHOL",59=>"TIP_NAMATRASNIKA",60=>"P3",61=>"TKAN_POKRITIJA",62=>"TKAN_CHEHLA",63=>"UROVEN_JESKOSTI_VERH",64=>"UROVEN_JESKOSTI_NIJ",65=>"FURNITURA",66=>"PRICE_LOWER",67=>"COLOR",68=>"P7",69=>"P6",70=>"WIDTH",71=>"H_MATRASA",72=>"H_SPAL_MESTA",73=>"",),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"DETAIL_SHOW_MAX_QUANTITY" => "N",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "Y",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "arrFilterCat",
		"FILTER_OFFERS_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_OFFERS_PROPERTY_CODE" => array(0=>"",1=>"",),
		"FILTER_PRICE_CODE" => array(0=>"RUB",),
		"FILTER_PROPERTY_CODE" => array(0=>"MANUFACTURER",1=>"SERIES",2=>"SERIA",3=>"COUNTRY",4=>"STRANA",5=>"",),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "1",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(0=>"",1=>"",),
		"LIST_OFFERS_LIMIT" => "0",
		"LIST_OFFERS_PROPERTY_CODE" => array(0=>"SLEEP_SIZE",1=>"MATERIAL",2=>"COLOR",3=>"SHIRINA",4=>"DLINA",5=>"VISOTA",6=>"GLUBINA",7=>"SIZE",8=>"DIAMETR",9=>"",),
		"LIST_PROPERTY_CODE" => array(0=>"PR100",1=>"NEWPRODUCT",2=>"PRICE_LOWER",3=>"MIN_PRICE",4=>"",),
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "belmebru",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "36",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(0=>"RUB",),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(0=>"NEWPRODUCT",),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "1",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("sections"=>"","section"=>"#SECTION_CODE#/","element"=>"#SECTION_CODE#/#ELEMENT_CODE#/","compare"=>"","smart_filter"=>"#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SKU_DESCRIPTION" => "N",
		"SHOW_TOP_ELEMENTS" => "N",
		"TEMPLATE_THEME" => "blue",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USE_ALSO_BUY" => "N",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_REVIEW" => "N",
		"USE_STORE" => "N",
                "CACHE_TYPE" => "N",  // Отключить кеш
                "CACHE_TIME" => 0,    // Время жизни кеша (0 = без кеша)
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>